### ISSUE TITLE
Should use babel for data_types.number.CURRENCY_SYMBOLS

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#224]
But I can't find a straightforward way to extract them

**Comment by JoeGermuska** [comment]
When this gets closed, would I no longer get this error?

`CastError: Can not parse value "$1504.88" as Decimal.`

**Comment by onyxfish** [comment]
Hmmm, you actually shouldn't be getting that now. $'s should be stripped...

**Comment by onyxfish** [comment]
Bug! I see why. Opening a new ticket.

**Comment by onyxfish** [comment]
@JoeGermuska Your issue is now fixed on master and will be fixed in the 1.0.1 release.

**Comment by onyxfish** [comment]
See comments on #602.
