### ISSUE TITLE
Extension: agate-dat

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#320]
Why not? http://datproject.readthedocs.org/en/latest/

**Comment by rdmurphy** [comment]
Something that may help with this, if it happens: https://github.com/karissa/datpy

It's already in [use with the California Civic Data Coalition folks](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/loadcalaccessrawfile.py#L71-L91)!

**Comment by onyxfish** [comment]
Neat! I was hoping to find a model, because frankly I have no idea how this should work.

**Comment by jpmckinney** [comment]
Closing as no demand expressed.
