### ISSUE TITLE
Explicit type check for row names that are ints

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#322]
Should probably error

**Comment by onyxfish** [comment]
I think we might want to rework this into a loop/generator so that it doesn't have to buffer a full list of true/false values into memory. That could add a lot of overhead for large datasets.

**Comment by nbedi** [comment]
Yup that sounds smart. My bad. I won't be able to fix it until tonight in case you need a fix sooner.

**Comment by onyxfish** [comment]
No big deal. It's not urgent. Whenever you can get to it.
