### ISSUE TITLE
If a column is entirely null TypeTester guesses it is Boolean

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#371]
Should probably be Text?

**Comment by onyxfish** [comment]
This doesn't actually matter that much given that the data is immutable anyway. Also, I'm not sure how to fix it without a (very slow) explicit check. Pushing out of the release.

**Comment by jpmckinney** [comment]
I think `TypeTester.run` can just do a quick return if `sample_rows` is empty. I'll let anyone who wants this feature to author the PR with a test.

**Comment by jpmckinney** [comment]
This is not clearly a bug, as the correct behavior is undetermined.

**Comment by jpmckinney** [comment]
In #704, people want to be able to force null columns to be Number, etc. so I don't think there is a clearly correct behavior, and the current behavior has not otherwise been reported as a bug, so closing.
