### ISSUE TITLE
print_tables and print_bars throws errors on Windows

### ISSUE THREAD

**Issue by mattwaite** [wireservice/agate#453]
I'm actively looking for a solution to this, but I wanted to log it in here so you were aware: On Windows, when users using Jupyter Notebooks try to print_table or print_bars with Agate, they get an error message that traces back to Babel. From a little scanning around, it seems that Babel is pretty insistent upon unicode and Windows command prompt is not unicode by default, so that may be the source of the issue. Here's the stack trace on the error message that is output by Jupyter Notebooks if anyone has any ideas. I'll report back on what switching to UTF-8 does or if something like Windows Powershell fixes the problem. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-6f6a8eb5f6b4> in <module>()
----> 1 big10.print_table()

C:\Users\DroneLab\Anaconda3\lib\site-packages\agate\table.py in print_table(self, max_rows, max_columns, output)
   1190             A file-like object to print to. Defaults to :code:`sys.stdout`.
   1191         """
-> 1192         print_table(self, max_rows, max_columns, output)
   1193 
   1194     def print_html(self, max_rows=None, max_columns=None, output=sys.stdout):

C:\Users\DroneLab\Anaconda3\lib\site-packages\agate\preview.py in print_table(table, max_rows, max_columns, output)
     84                 v = ''
     85             elif number_formatters[j] is not None:
---> 86                 v = format_decimal(v, format=number_formatters[j])
     87             else:
     88                 v = six.text_type(v)

C:\Users\DroneLab\Anaconda3\lib\site-packages\babel\numbers.py in format_decimal(number, format, locale)
    253         format = locale.decimal_formats.get(format)
    254     pattern = parse_pattern(format)
--> 255     return pattern.apply(number, locale)
    256 
    257 

C:\Users\DroneLab\Anaconda3\lib\site-packages\babel\numbers.py in apply(self, value, locale, currency)
    654             b = b or '0'
    655             a = self._format_int(a, self.int_prec[0],
--> 656                                  self.int_prec[1], locale)
    657             b = self._format_frac(b, locale)
    658             number = a + b

C:\Users\DroneLab\Anaconda3\lib\site-packages\babel\numbers.py in _format_int(self, value, min, max, locale)
    698         gsize = self.grouping[0]
    699         ret = ''
--> 700         symbol = get_group_symbol(locale)
    701         while len(value) > gsize:
    702             ret = symbol + value[-gsize:] + ret

C:\Users\DroneLab\Anaconda3\lib\site-packages\babel\numbers.py in get_group_symbol(locale)
    206     :param locale: the `Locale` object or locale identifier
    207     """
--> 208     return Locale.parse(locale).number_symbols.get('group', u',')
    209 
    210 

AttributeError: 'NoneType' object has no attribute 'number_symbols'

**Comment by onyxfish** [comment]
Matt, I have a suspicion that your having the same issue tracked:

http://babel.edgewall.org/ticket/98

(Also [here](http://stackoverflow.com/questions/4838056/python-why-do-i-get-this-exception-from-babel-when-calling-from-cron).)

Can you try setting that environment variable and see if that fixes things? (It would also be good to know if this var is set by default in Powershell, et al.)

**Comment by tonypapousek** [comment]
I think I've found a temporary solution:

By using the bash shell included with the standard Git installation, I can make Matt's command run in Jupyter (or directly via the python interpreter).

The whole thing is running through Python 3.5.1 :: Anaconda 2.4.1, _without_ activating a conda environment.

I'm unable to activate/source activate into any environment other than root. I'll have to tinker around with my ~/.bashrc profile to activate those properly.

Because python isn't used by any system-critical Windows scripts, it could be considered "safe" to run without switching to an environment.

This isn't ideal, but it works.

**Comment by mattwaite** [comment]
Can confirm Tony's workaround. I've tried setting the system locale, I've set it explicitly it in the basic command prompt and in Powershell, but when running it in the Anaconda environment, it breaks. So somewhere along the way, the environment variable is getting stripped (by Anaconda, by Jupyter, by Windows, by the shell I'm using? Don't know.) That Git Bash works makes me think Cygwin or any other Unix like terminal emulator will too. This will get me through today's class. I'll keep working on a solution and report back. This doesn't seem to be an Agate issue, so I'll close this.

**Comment by onyxfish** [comment]
@tonypapousek @mattwaite Thanks to both of you for reporting. I'm going to reopen this to say if there is way I can opt into a safer default. (`utf8` if not specified)

**Comment by palewire** [comment]
I can report that today I saw this same error trip up one of our Windows users when they tried a ``print_table``. Sad to say it's blocking their introduction to agate entirely. Is there a way to turn off babel somehow or pass in a default manually?

**Comment by palewire** [comment]
After a little study, I suspect an experimentation on a Windows shell with the bug, I suspect that passing in the ``locale`` keywoard argument explicitly [here](https://github.com/onyxfish/agate/blob/master/agate/preview.py#L87) with the Number objects setting can fix the problem.

Within babel, [that keyword argument](https://github.com/python-babel/babel/blob/master/babel/numbers.py#L226) is set to [a global default](https://github.com/python-babel/babel/blob/master/babel/numbers.py#L28) that is sniffed off the system. On the Windows machine I was using, the sniffer returned a null value and I got the same error as Matt. When I substituted ``en_US`` as the override everything worked fine. 

So I hope if we can get the Number to pass in its ``self.locale`` attribute the linked line above we'll be back in business.

**Comment by onyxfish** [comment]
Yeah, I think using the locale specified on the `Number` is correct. There might be a way to shoehorn this into `make_number_formatter`, but it's not obvious to me. I think instead I'd just add...

```
locale = table.column_types[j].locale
```

...on the line before. And then pass that into `format_decimal`. Seems like it should work to me.

We also need to fix it in `print_bars` and grep the code for any other occurrences of `format_decimal` that might have the same problem.

**Comment by onyxfish** [comment]
Ah ha, I see now you had already beat me to this. Woops.

**Comment by onyxfish** [comment]
Fixed for `print_table`. Still need to fix for `print_bars`.

**Comment by palewire** [comment]
The ``print_bars`` call in ``example.py`` does now work for me with the fix in #488 but I can't speak for others.

**Comment by onyxfish** [comment]
Ah my bad, I glanced at the patch and didn't see edits to `print_bars`, but I was just scanning too quickly. Thanks!

**Comment by palewire** [comment]
No problem. The key change we made was that new global call at the top that falls back to default when Windows shits out.
