### ISSUE TITLE
Table.join should have a columns kwarg

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#479]
Resisted this because it provides two ways to do the same thing, but I constantly find myself wanting it and it's a super cheap optimization.

Should default to all columns not in right_key.

**Comment by onyxfish** [comment]
I phrased this ticket badly. I only meant for the kwarg to apply to those columns in the righthand table. The equivalent of being able to say "given this usps, join me only the state name from the state details table". I don't think it's particularly useful at this point to be able to filter columns from the lefthand table and it makes it somewhat onerous to have to list every column you want to keep.

**Comment by nbedi** [comment]
Sorry about that, should be good now.

**Comment by onyxfish** [comment]
My fault. Thanks for updating it. :+1:
