### ISSUE TITLE
Is there was a get a list of all the distinct values in a column?

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#498]
If I understand it right, the ``Table.distinct()`` method returns a Table object with a list of distinct rows in it. 

Don't have any problem with that, but here's a related use case I'm looking for a way to satisfy: Can I get the table to return a list with all the distinct values from a particular column?

For instance, let's say I have this table.

```python
import agate
column_names = ['name', 'race', 'gender']
column_types = [agate.Text(), agate.Text(), agate.Text()]
rows = (
    ('joe', 'white', 'male'),
    ('jane', 'white', 'female'),
    ('josh', 'black', 'male'),
    ('jim', 'latino', 'male'),
    ('julia', 'white', 'female'),
    ('joan', 'asian', 'female'),
)
people = agate.Table(rows, column_names, column_types)
```

And here's the kind of thing I would like to do, in psuedo code:

```python
print people.distinct_values("race")
['white', 'black', 'latino', 'asian']
```

There might be a good way to do this I'm missing. Forgive me if I missed it.

**Comment by nbedi** [comment]
Best way I can think of is `set(table.columns['race'].values())`

**Comment by palewire** [comment]
Would opposed to adding a higher level method to pull that kind of thing?

**Comment by nbedi** [comment]
Hmm I may defer that to @onyxfish. It's at the weird intersection of improving human usability and adding to code bloat.

**Comment by palewire** [comment]
Thanks. Another idiom I can imagine that might be any better worse might be something chained on a select statement.

```python
people.select("race").distinct("race").columns['race'].values()
```

**Comment by palewire** [comment]
As I think about this, I can imagine another trick on the column object that I think I like even better.

```python
people.columns['race'].distinct()
```

**Comment by nbedi** [comment]
Agreed, it could be a method on `MappedSequence` so it can work on rows and columns (even though it's more relevant to columns)

**Comment by nbedi** [comment]
Added a values_distinct method to Column.

To be clear, what you mentioned does work:

`people.distinct('race').columns['race'].values()`

but now this also works:

`people.columns['race'].values_distinct()`

**Comment by palewire** [comment]
Thanks. Would a cookbook entry on this be a helpful thing I could add?

**Comment by nbedi** [comment]
Sure! I'm not exactly sure where the best place for it would be

**Comment by palewire** [comment]
IMHO the best cookbooks are the biggest ones.

**Comment by nbedi** [comment]
:+1:

**Comment by palewire** [comment]
Done https://github.com/wireservice/agate/pull/504

**Comment by onyxfish** [comment]
Looks good. Happy with where this ended up. It's useful to have a memoized hook for this for aggregations that need a distinct list too.
