### ISSUE TITLE
I think the bar chart symbol is throwing errors when I try to save an Jupyter Notebook to PDF

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#500]
I've been happily using agate in a Jupyter notebook. But when I try to do the standard "save as PDF" option it throws this error:

```
! Package ucs Error: Unknown Unicode character 9619 = U+2593,
    (ucs)                possibly declared in uni-37.def.
```

I googled that Unicode character and it appears to be [the bar chart symbol](http://www.fileformat.info/info/unicode/char/2593/index.htm).

**Comment by nbedi** [comment]
I messed around with this and the bar chart symbol is causing the issue. Seems to be related to https://github.com/ipython/ipython/issues/7150, ipython uses pdflatex for pdf conversion but it does not have complete unicode support. 

They mention a work around in that issue but we should probably use a different character to avoid this problem. Issue is choosing one that is supported and looks appealing...

**Comment by palewire** [comment]
I'll let you guys decide, but saving a notebook to PDF is one of our chief ways of sharing our analysis with editors and reporters around the newsroom so I'd love a fix.

**Comment by nbedi** [comment]
Added an optional fix, pass `printable=True` to print_bars. It's not as pretty but works. Let me know if it works for you.

**Comment by palewire** [comment]
Totally up to you. Though if the root cause of this problem recurs you might have to revisit this bug. Or if people other than me want to print to PDF. It's a use case I'm trying to popularize here at our office but it who knows it could be rare.

**Comment by onyxfish** [comment]
Reopening this one because I want to noodle on it a bit.

**Comment by onyxfish** [comment]
I cleaned up this code a little bit but otherwise couldn't find a better solution.

**Comment by palewire** [comment]
I suspect the only solution is either a patch to the ``nbconvert`` library that does the printing, or substituting in another bar chart character. I suppose you could also allow users to substitute their own bar chart character.
