### ISSUE TITLE
Add GitHub contributing docs

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#503]
With new GitHub support for [issue and pull request templates](https://github.com/blog/2111-issue-and-pull-request-templates), we should add `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` to `.github/` at root.

**Comment by onyxfish** [comment]
Def agree.

**Comment by onyxfish** [comment]
Ah, just saw you already did it. Looks great!

**Comment by nbedi** [comment]
Still need the templates but never got to figuring out the best way to format them. I don't want the templates to be intimidating since I'd prefer more people feel welcome submitting issues/PRs.

**Comment by onyxfish** [comment]
I totally agree. There also just isn't a lot of "standard" data I feel like we need for debugging. Maybe we just skip the templates?

**Comment by nbedi** [comment]
:+1:
