### ISSUE TITLE
Need a test for error when attempting to edit row values

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#505]
We should have test for #502 since it deviates from the `Mapping` contract. Will help to keep things tidy if we ever modify this implementation.

**Comment by nbedi** [comment]
My bad, thought `test_get_invalid` covered it. Is it because we don't have a specific test on getitem?

**Comment by onyxfish** [comment]
I don't think `test_get_invalid` will cover the case where you try to a set a value on an existing "cell", right? Seems like we should have have a specific test for the setter?

**Comment by nbedi** [comment]
Ahh oops. Yup, totally misread that test. Thanks for catching that!

**Comment by onyxfish** [comment]
Sure thing. Haven't had a lot of time for agate the last few weeks, but trying to do a quick look over what's changed while I've got an hour.

**Comment by nbedi** [comment]
:+1: I'll throw in a fix for this too
