### ISSUE TITLE
Both `Table.counts` and `Table.percents` should be superseded `Table.pivot`

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#508]
They are just special cases of it... but that assumes we can make it work.

**Comment by onyxfish** [comment]
These actually don't turn out to be quite the same thing. One is a row-wise solution and the other is a column-wise solution. Need to think a bit more about what is "correct".

**Comment by onyxfish** [comment]
These are now equivalent:

```
a = table.counts('county')

a.print_table(max_rows=10)

b = table.pivot('county')

b.print_table(max_rows=10)
```

Output:

```
|-------------+--------|
|  county     | count  |
|-------------+--------|
|  ALLEN      |    18  |
|  ANDERSON   |     9  |
|  BARTON     |    40  |
|  BOURBON    |    14  |
|  BROWN      |    13  |
|  BUTLER     |    23  |
|  CHAUTAUQUA |    32  |
|  CHEROKEE   |    31  |
|  CHEYENNE   |    29  |
|  CLAY       |     8  |
|  ...        |   ...  |
|-------------+--------|
|-------------+---------|
|  county     | Length  |
|-------------+---------|
|  ALLEN      |     18  |
|  ANDERSON   |      9  |
|  BARTON     |     40  |
|  BOURBON    |     14  |
|  BROWN      |     13  |
|  BUTLER     |     23  |
|  CHAUTAUQUA |     32  |
|  CHEROKEE   |     31  |
|  CHEYENNE   |     29  |
|  CLAY       |      8  |
|  ...        |    ...  |
|-------------+---------|
```

**Comment by nbedi** [comment]
And now I'm assuming `table.pivot('county', computation=Percent('pivot'))` works for `Table.percents`

**Comment by onyxfish** [comment]
Correct, it does. Examples of both are also in the new docs: http://agate.readthedocs.org/en/latest/cookbook/transform.html

**Comment by onyxfish** [comment]
Still waffling on this. Once #514 is closed, `counts`, `percents` and `bins` could all be implemented as special cases of `pivot`. These three cases *might* justify shorthand methods specifically because of their utility in generating histograms. (Which was the whole reason I wrote `counts` to begin with.)

On the other hand, this could just be treated as a documentation problem. They are all one-liners, even when written using `pivot`.

**Comment by onyxfish** [comment]
Alternately, we could kill `counts` and just add a `print_histogram` method that incorporated the pivot statement.
