### ISSUE TITLE
There should probably be a `Table.unpivot` method

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#512]
It's not clear how useful this is, but it's pretty obvious how it would work so it would be nice to have the inverse of `Table.pivot`.

**Comment by nbedi** [comment]
This isn't immediately obvious to me since `Table.pivot` loses data. What would the output table be?

**Comment by onyxfish** [comment]
Ha, so it isn't obvious then! I think it would just be a repeated row for every count. However, now that I think about it, this could only work for the `Length` case, which seems like such a trivial subclass, let's just not do it!
