### ISSUE TITLE
Count by lambda

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#521]
Since Count is changing a bit, wondered if adding the option to count by a given lambda that takes a row and returns boolean was a good idea. The custom statistics cookbook might need to be changed for a better example of aggregations.Summary then.

**Comment by onyxfish** [comment]
Hmmm, I don't feel strongly about this one way or another. I'm all for supporting lambdas where we can, but it also like this is pretty well covered by `Summary`.

**Comment by nbedi** [comment]
Eh then let's not for now. Closing this.
