### ISSUE TITLE
Agate2 ideas

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#523]
Back to an old set of ideas, but maybe better this time?

* Formally eliminate logical distinction between columns and rows.
* MappedSequence remains the logical base class, but the difference between rows and columns is removed for processing.
* Computation -> Map
* Aggregation -> Reduce
* Column names and row names are just sequence names. Item names (row['foo'], column['bar']) are just value names. 
* Add a "Mixed" DataType that effectively prohibits reduce operations. (Default for "rows"/non-primary sequences.)

Possibly some notion of a `DependentSequence` that implements the physical cross-referencing from the way the data is stored to the its logical structure. (`column = [row[c] for row in table]`)

The question, as always: can this be implemented while maintaining the table-independence of the "rows"/independent sequences. Maybe be moving the cross-referencing into the sequence dependent sequence logic, rather than the `Table`.

**Comment by nbedi** [comment]
- Make defining a new computation or aggregation easier/more immediately intuitive. Maybe through a reimplementation of `Formula` and `Summary`

**Comment by onyxfish** [comment]
The hitch with collapsing rows and columns remains that only one can be guaranteed to be strongly typed. Possible implementation solution:

* There are two types of sequence: `Sequence` and `TypedSequence`. If column types are specified, then they would be of `TypedSequence`. Same for rows.
* If any operation that requires typing in a certain dimension is invoked then the first is to check if those dimensions are `TypedSequence`. If not, error out.
* All of this would be invisible to the ordinary user, but would also allow for more esoteric cases, such as "horizontal" data series.

**Comment by onyxfish** [comment]
So I hacked on this idea some more as part of optimization testing and I just don't think it's a good idea. Refactoring to break down the walls between Rows and Columns really makes the API a lot more complicated. (Things like row naming become a lot harder.) It's also going to be slower for a subset of operations. And lastly it inherits a lot of the problems of general Map/Reduce frameworks. It just won't be as flexible as it is now.

With all those things enumerated, I'm going to close this ticket. I still think that, in an ideal world, this is the path we would pursue, but I don't think it's practical. If anybody wants to take a whack and it and prove me wrong, more power to you.
