### ISSUE TITLE
Print table should have a global `max_precision` argument

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#544]
Annoying when calculated variables get printed with unlimited accuracy

**Comment by palewire** [comment]
+1

I think a sensible default would be much lower than what we current have. Right now, a percentage column prints out like this:

```
|-------------+----------------+-----------------------|
|-------------+----------------+-----------------------|
|  SEDGWICK   |     977,174.45 | 23.67860376872521...  |
|  COFFEY     |     691,749.03 | 16.76225896897939...  |
|  MONTGOMERY |     447,581.20 | 10.84565595133044...  |
|  JOHNSON    |     420,628.00 | 10.19253393908462...  |
|  SALINE     |     245,450.24 | 5.947677999459061...  |
|  ...        |            ... |                  ...  |
|-------------+----------------+-----------------------|
```

I think it should be something more like this:

```
|-------------+----------------+-----------------------|
|-------------+----------------+-----------------------|
|  SEDGWICK   |     977,174.45 | 23.68...  |
|  COFFEY     |     691,749.03 | 16.77...  |
|  MONTGOMERY |     447,581.20 | 10.85...  |
|  JOHNSON    |     420,628.00 | 10.19...  |
|  SALINE     |     245,450.24 | 5.95...  |
|  ...        |            ... |                  ...  |
|-------------+----------------+-----------------------|
```

**Comment by onyxfish** [comment]
Ideally, the default would be somehow responsive to the precision of the numbers, with a smarter default (2?) for maximum precision numbers that are likely to have been the result of math. Alternatively, it could just be 3-5. The ellipsis ensure it's clear the number has been rounded.

**Comment by palewire** [comment]
Maybe there's a clever trick to that. If the precision is two to five, keep it. If it's greater than five trim to two. Or insert whatever other number makes sense.

**Comment by orsharir** [comment]
It seems like it would be very simple to implement this, so is there a reason this hasn't been implemented yet? If I were to submit a pull-request adding this, would it be accepted?

(Side note: really loves this library. Very Intuitive and readable!)

**Comment by nbedi** [comment]
@orsharir please feel free to open a pull request and we will take a look!

**Comment by nbedi** [comment]
@onyxfish @palewire The current solution does not use a 'smart' default that you were discussing a while back. We can open a new issue for it if you still want it.

**Comment by orsharir** [comment]
I would argue that it is better to keep the operation simple and easy to understand, especially for the default behavior.
