### ISSUE TITLE
Boolean type inference/conversion (1/0 => True/False) and table.to_csv()

### ISSUE THREAD

**Issue by whyvez** [wireservice/agate#545]
Is there a way to disable the implicit casting of binary truth (1/0) boolean columns to Python (True/False) values. It does not cause too may issues in reading since we are in Python land. When it comes to writing back to csv and especially in a multi-language environment it does causes issues. Every languages have different casings for boolean values; javascript (true/false); R (TRUE/FALSE). Binary (1/0)  on the other hand is standard across all languages.

Is there an existing facility to override this in the writing back to csv?

Furthermore; changing 1/0 to True/False seems wrong since the raw data is changed. Seems like efforts have been taken to make data immutable using tuples but yet the data gets implicitly casted on parsing. Maybe I am nit understanding the intent or there might be an easy way to disable this.

All an all this package is my favourite discovery of the month. Great job!

**Comment by onyxfish** [comment]
Hi Yves, there are a variety of ways you can disable the 1/0 detection, depending on your needs:

* Override the column type to `agate.Number()` either by specifying column names or using an instance of `TypeTester`.
* Pass different `true_values` and `false_values` to `agate.Boolean()`.
* Completely remove `agate.Boolean()` from the `TypeTester`'s `types` argument.

On the more philosophical point, I don't think of parsing as modifying the data. The goal is create the best possible Python representation of what the data means. (CSV is, after all, just a serialization format.) In my experience a column that contains exclusively 1/0 values is probably boolean and the way to represent booleans in Python is `True` and `False`.

We could, I suppose, support some custom serialization handlers in the CSV serializer. (There is already a sort of hook for this, though [its a noop](https://github.com/wireservice/agate/blob/master/agate/data_types/base.py#L41) for `agate.Boolean`.) If you wanted to work up a pull request I'd take a look at it.

One landmine in doing this, the `DataType` subclasses are really only meant to affected input parsing, so it's honestly probably not the right place for such a thing to live if it's going to be generalized to allow user customization.

**Comment by onyxfish** [comment]
Reading back on my comment, I probably should have put the 2nd suggestion first in the list, since that's probably the one you want in your case.

Oh and thanks for the kudos! Much appreciated!

**Comment by whyvez** [comment]
Christopher, 
Thank you for your quick response. 

I went with the third option you suggested:

```
tester = agate.TypeTester(types=[
    agate.Number(),
    agate.TimeDelta(),
    agate.Date(),
    agate.DateTime(),
    agate.Text()
])
```

Would there be a strategy that would be more global? I tried changing the DEFAULT TRUE/FALSE constant for the Boolean type without success but I might have implemented it improperly.

**Comment by onyxfish** [comment]
Yves, there isn't currently a global way of changing that variable, though you could subclass TypeTester to change the default and then just use your own implementation everywhere.

**Comment by onyxfish** [comment]
Closing this out since there is a working solution for this edge-case.
