### ISSUE TITLE
Boolean type inference/conversion (1/0 => True/False) and tester(limit=)

### ISSUE THREAD

**Issue by whyvez** [wireservice/agate#546]
The boolean type inference is causing problems during the parsing of datasets when certain conditions are met. 

My current condition is a dataset with a csv of 1100 columns and 30000 rows. In order to optimize the parsing of the csv file I tried setting the tester limit to 100, 1000 and 5000 but the parser always blows chunks on the boolean inferences. I am suspecting that the initial x number of rows are indeed 1's and 0's or other and the type checker detects the column as boolean.

I am wondering if the boolean datatypes could possibility be inferred later or optimally at the end of the parsing. The column would be treated as Number until the very end.  At end of parsing if column contains only 1's and 0's type it as boolean then.

Hopefully this makes sense.

**Comment by onyxfish** [comment]
Hi again, Yves. Your explanation of what's happening sounds correct. As a short term solution I'd take a look at my suggestions on your other ticket.

1,100 columns is... special data. I'll be curious to hear how that works for you once you get it loaded up. In terms of deferring the Boolean testing until the end, the current structure of the code doesn't allow it and I think it would be pretty tricky to implement without deoptimizing the whole type inference process.

My gut reaction says that the right solution here is to just customize the TypeTester to the data you've got. I don't want to blow up the type inference systems for an edge-case. That being said, if this comes up frequently I'd happily revisit.

**Comment by whyvez** [comment]
Christopher, Yes you are right now that I know how to alter the type tester I have removed some unnecessary checks and the data is loading faster than with all the checkers in place. I will be doing some more tests today with this dataset and will report back with metrics. I am also doing a pivot on the entire dataset which should be interesting.
