### ISSUE TITLE
Table.print_table should ensure decimal points line up, even if numbers have different precision

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#553]
Related to #544.

**Comment by onyxfish** [comment]
Hey, so I've reverted this commit for two reasons:

1. It doesn't do quite what I had in mind for this ticket. The intention (perhaps poorly described) was that the decimals would align like this:

```
   1.234
  12.3
 122.756
```

Though now that I look at that, maybe this would make more sense:

```
   1.234
  12.300
 122.756
```
  
2) The computation happening in `max_precision` doesn't take into account the space consumed by the formatting characters, so it can't produce a precise output.

There probably is an iteration on what you did that'll get a good solution, but I'm itching to push a release out the door, so I've just reverted it for the moment.

**Comment by nbedi** [comment]
No worries, sounds good

**Comment by nbedi** [comment]
I think I hooked on to max_precision to avoid looping through values again but print_table isn't really going to be used to print massive amounts of data. My fear of redundancy was a little too strong.

**Comment by jpmckinney** [comment]
Closed by #633.
