### ISSUE TITLE
Would column headers generated by the pivot be better and more descriptive if they included the computation type?

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#555]
Here is the example output now, which doesn't specifically tell you want it did

```
+---------+--------+--------+
| race    | male   | female |
+=========+========+========+
| white   | 0      | 1      |
+---------+--------+--------+
| asian   | 1      | 1      |
+---------+--------+--------+
| black   | 0      | 2      |
+---------+--------+--------+
| latino  | 1      | 0      |
+---------+--------+--------+
```

Maybe it could nicer if it did something like this instead?

```
+---------+--------------+--------------+
| race    | male_count   | female_count |
+=========+==============+==============+
| white   | 0            | 1            |
+---------+--------------+--------------+
| asian   | 1            | 1            |
+---------+--------------+--------------+
| black   | 0            | 2            |
+---------+--------------+--------------+
| latino  | 1            | 0            |
+---------+--------------+--------------+
```

**Comment by onyxfish** [comment]
I seriously considered this, but I don't think it's usually what I want. For one thing, it really makes it harder to reference the columns, especially in any automated fashion. For another, it's not obvious what the automated column name for something like "MaxLength" would be. And for a third, why note `white_count` in the first row? It has the same semantics as the first column.

**Comment by palewire** [comment]
You make really good points. Here's the common use case where it comes up for us: We want to pivot by a column, like gender, and print out both the frequency counts and the percentage totals. 

Our habit with other tools has been to toss all that into one big table. If there were five race categories, we would add five count columns and then five more percent columns.

With this configuration, I suspect you would advise we create and print two different tables, the first with counts and the seconds with percentages? Is that right?

**Comment by onyxfish** [comment]
Yeah, either that, or, rename the columns after the tables are created. The workflow def isn't as seamless for that particular case.

**Comment by palewire** [comment]
How would the renaming work?

**Comment by onyxfish** [comment]
It's not beautiful code or anything, but something like this should work:

```
names = table.column_names
new_names = names[0] + ['%s_count' % name for name in names[1:]]
table = table.rename(new_names)
```

**Comment by palewire** [comment]
Got it. The other thing I can think of at the moment would be some system for the computation type being stored in the "metadata" of the columns and displayed in some other format, like a second column grouping header stacked atop the existing headers.

**Comment by onyxfish** [comment]
An earlier version of agate had a provenance feature that connected every derived table/column to its parents. That got cut largely because every table needed to hold a reference to previous versions, which meant memory never got released for intermediate tables, which simply destroyed performance.

I can imagine some way of serializing the process of what created a column, but honestly, I'd have to see a very compelling use case to consider adding all that instrumentation purely for display purposes.

**Comment by onyxfish** [comment]
Upon rereading, I'm standing by the original design decision on this. Closing out.
