### ISSUE TITLE
Is there a way to create a table from a list of dictionaries?

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#557]
It's a pretty common use case in our parts to want to analyze data in memory that is a list of dictionaries. Is there a way for agate to slurp this up? And if not, can we figure out a way to add it?

Here's what happens now.

```python
import agate

data = [
    dict(column_one='a', column_two=1),
    dict(column_one='b', column_two=2),
]

table = agate.Table(data)
table.print_table()

RuntimeWarning: Column names not specified. "('a', 'b')" will be used as names.
  table = agate.Table(data)
Traceback (most recent call last):
  File "scratch.py", line 8, in <module>
    table = agate.Table(data)
  File "/home/ben/Code/agate/agate/table.py", line 157, in __init__
    self._column_types = column_types.run(rows, self._column_names)
  File "/home/ben/Code/agate/agate/data_types/__init__.py", line 93, in run
    if len(row) > i and not column_type.test(row[i]):
KeyError: 0
```

**Comment by onyxfish** [comment]
If I'm understanding the data structure correctly, Table.from_object is almost, but not quite, what you want. I'd accept a patch adding an argument to that to support "unkeyed" objects.

http://agate.readthedocs.org/en/1.3.0/api/table.html#agate.table.Table.from_object

**Comment by palewire** [comment]
That actually seems to work great. I think you might just need an example in the documentation. That's the only place I looked.

**Comment by palewire** [comment]
I will submit a pull request shortly.

**Comment by palewire** [comment]
PR is in at #558
