### ISSUE TITLE
DateTime string inferred as Date

### ISSUE THREAD

**Issue by ursetto** [wireservice/agate#568]
A string which appears to be a valid datetime may be inferred as a date instead, chopping off the time.

```
 >>> tt = agate.data_types.TypeTester()
 >>> type(tt.run([ ("2015-01-01 02:34",) ], ("date",))[0])
 <class 'agate.data_types.date.Date'>
```

But forcing the type to DateTime parses it fine.

```
>>> tt = agate.data_types.TypeTester(force={ 'date': agate.DateTime() })
>>> type(tt.run([ ("2015-01-01 02:34",) ], ("date",))[0])
<class 'agate.data_types.date_time.DateTime'>
```

Date() is preferred to DateTime() in TypeTester.  In Date(), self.parser.parseDT parses as a datetime and returns status==3, which is not accepted.  isodate.parse_date is then used to parse the string, which succeeds, but chops off the time (as it encounters a space instead of `T`).  It seems that the permissive ISO date parsing is the issue here.

```
>>> isodate.parse_date("2015-01-01 02:34")
datetime.date(2015, 1, 1)
>>> isodate.parse_datetime("2015-01-01 02:34")
isodate.isoerror.ISO8601Error: ISO 8601 time designator 'T' missing. Unable to parse datetime string '2015-01-01 02:34'
```

Workaround is to force DateTime() type, or set an explicit date format.

**Comment by onyxfish** [comment]
Thanks for the detailed bug report, Jim. It sounds like this may be a regression from the most recent set of changes to the date parser. We'll add a unit test for that specific format and figure out how best to fix.
