### ISSUE TITLE
Exonerations data in tutorial has weird states, e.g. `F-TX`

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#570]
Cleaning this up should be part of the analysis.

Via @livlab: https://docs.google.com/document/d/1dVG876aVZoDxW5RyWBM7kC1ZTyPTrWqKBJctLuAh7gs/edit?ts=56e71c0e

**Comment by nbedi** [comment]
Reached out to the registry and found out that 'F-' stands for federal cases. Sounds like the right way to clean up would be to create a new boolean federal column for federal cases and then replace the state column with a clean state abbreviation only column.

**Comment by onyxfish** [comment]
Nice, I like that you used it as an opportunity to demonstrate `replace`.
