### ISSUE TITLE
Can I group_by more than one column?

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#577]
```python
table.group_by('column_one', 'column_two').aggregate([
    ('trump', agate.Sum('column_three')),
    ('total', agate.Sum('column_four')),
]).print_table()
```

It did not work. It only grouped by the first column. 

I would like to be able to do this.

**Comment by onyxfish** [comment]
You can do this, but you have to chain the calls. This should be more explicit in the documentation.

```
table.group_by('column_one').group_by('column_two').aggregate([
   ...
```

**Comment by palewire** [comment]
Thank you. I will submit a PR with documentation shortly.
