### ISSUE TITLE
It would be cool if I didn't have to use TypeTester to override one or two column types

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#580]
Today I'm working with a CSV with a dozen columns. Ten of them import fine automatically, but two need an override so the data types come out correct. To fix the problem I've done something like this:

```python
tester = agate.TypeTester(force={
    'column_one': agate.Text(),
    'column_two': agate.Number(),
})
table = agate.Table.from_csv(csv_path, column_types=tester)
```

This is all fine and dandy. It works well. I can't complain too much.

However, the ``TypeTester`` code is a bit verbose with that nested dictionary. I doubt I'll ever be able to memorize that, and I suspect it might be tough for Python newbies to follow.

Would it be ridiculous to image something a little bit simpler like this?

```python
column_types = {
    'column_one': agate.Text(),
    'column_two': agate.Number(),
}
table = agate.Table.from_csv(csv_path, column_types=column_types)
```

**Comment by ejmurra** [comment]
Seems to me that a solution would be to check the type of whatever is passed as a column_types kwarg and casting a dict to a new instance of TypeTester. If that's an agreeable solution, @onyxfish, I'll implement it.

**Comment by nbedi** [comment]
@ejmurra sounds right to me

**Comment by onyxfish** [comment]
Yep I'm onboard with this. @ejmurra go for it!
