### ISSUE TITLE
Skip rows on from_csv 

### ISSUE THREAD

**Issue by lindzcook** [wireservice/agate#581]
It would be cool if there was either a boolean parameter that allowed lines to be skipped in a csv when a table was loaded (could default to false) or a number of lines to skip (could default to zero). Lots of gov files have notes at the top before the real data start. 

For example, first 7 lines of Clinton's FEC contributor file: 

```fec.gov
"title","Two Year Summary"
"description",2016""
"timestamp",24-FEB-16
"copyright","Copyright 2012, Federal Election Commission."
"cmte_id",P00003392
"cmte_nm","CLINTON, HILLARY RODHAM"
```

Trying to load this csv into a table currently throws the following error: 

`ValueError: Row 0 has 2 values, but Table only has 1 columns.`

**Comment by nbedi** [comment]
Sounds good to me. I think number of lines makes most sense for an input parameter. @onyxfish have you thought about this before when working on csvkit?

**Comment by therden** [comment]
Yes please!  

I regretted this missing feature *just this week*.  

I've been hoping to use **agate** for awhile now, and thought I had a golden opportunity in a project I was working on two days ago.  But after downloading 10 years' worth of monthly data files from NOAA, the 7-line header in each file prevented me from loading them using *from_csv*, and I was forced to turn to **pandas** instead.

**Comment by onyxfish** [comment]
Yep, totally agree with having a number of lines to skip. In fact, csvkit has this, so this is a regression.

**Comment by nbedi** [comment]
I added a `skip_lines` argument to `Table.from_csv`. It can be an int as discussed and it can also be a sequence of line indexes to cover some additional cases mentioned in https://github.com/wireservice/csvkit/issues/336
