### ISSUE TITLE
I wish there was a **computation** for Sum that would combine columns 

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#583]
Unless I'm missing something (and lord knows I've missed many somethings), the current `agate.Sum` tool only works as an "aggregation" that will add up every value in a single column. 

I'm glad that's there. But I wish there was a similar tool for appending a new column to a table that is the sum of one or more other columns. 

This came up today in our work when we were working with some Census data. The source table has a row for every Census tract in California and dozens of columns with arcane names. We'd like to group those columns together into four or five neat groups. 

Here's a simplified version of how we're solving that right now. Our design pattern is based upon an example found in the Excel portion of the cookbook.

``` python
def compute_less_than_high_school(row):
    columns = [
       'B15002_001E',
       'B15002_002E',
       'B15002_003E',
       'B15002_004E',
       'B15002_005E',
   ]
   return sum(tuple(row[c] for c in columns))

def compute_high_school_graduate(row):
   columns = [
       'B15002_006E',
       'B15002_007E',
       'B15002_008E',
       'B15002_009E',
       'B15002_010E',
   ]
   return sum(tuple(row[c] for c in columns))

table = table.compute([
    ('less_than_high_school', agate.Formula(agate.Number(), compute_less_than_high_school)),
    ('high_school_graduate', agate.Formula(agate.Number(), compute_high_school_graduate)),
])

table.select(["NAME", 'less_than_high_school', 'high_school_graduate']).limit(10).print_table()
```

That does work, but I'd love to do something a little more like this.

``` python
table = table.compute([
    ('less_than_high_school', agate.Sum(['B15002_001E', 'B15002_002E', 'B15002_003E', 'B15002_004E', 'B15002_005E',]),
    ('high_school_graduate', agate.Sum(['B15002_006E', 'B15002_007E', 'B15002_008E', 'B15002_009E', 'B15002_010E',]),
])
```

While that's my dream, it does raise a problem in my mind. 

Given the current namespacing of the `agate` module, how does a user know whether they are using an aggregation or a computation? Should those methods be able to perform both functions? If so, how are the options managed? If not, should the namespacing be more explicit about the limits? 

I don't know the answers but I'd like to raise the issue because I see this as a very common use case that I would love to see simplified in the API.

**Comment by nbedi** [comment]
Removing the distinction between `rows` and `columns` (#523) could solve this really cleanly. Then Aggregations could run on rows and it would be possible to compute new columns from aggregations (sort of like your second piece of code). `Sum` and other aggregations would need to accept a subset of a row/column to actually work in this case.

This also makes a lot of sense to me since `Aggregations` and `Computations` would no longer be bound to the concept of `columns` and `rows` and would instead be bound to their purposes (reduce and map). This use case would then simply be mapping a new column to a series of reductions on the rows. 

(This may take a bit of time though...)

**Comment by palewire** [comment]
That's an interesting solution that hadn't occurred to me because I'm not familiar with many those internal functions of agate. If there's something I could do to, in the words of the Phifer, ["push it along,"](https://www.youtube.com/watch?v=qRPvKh4JCLg) please let me know.

**Comment by nbedi** [comment]
Also in the words of Phife, _you'll be doing us a really big favor_ just by continuing to open great issues like this. The implementation itself will end up taking a lot of work cause it changes some core functionality and will break plenty of code. This did get me excited though so I'll probably play with it on my fork this week. Hopefully not too much goes wrong.

**Comment by onyxfish** [comment]
I've got mixed feelings about the specific case being described here (consolidating an operation that crosses both rows and columns into a single operator). But that being said, I do think it's a good example to press on the distinction that @nbedi is getting at. There is really not essential reason that `Aggregation` and `Computation` need to be divided the way they are now. It's just complicated to unravel them.

I'll have to mull on this more.

**Comment by jpmckinney** [comment]
Since the library is in maintenance mode, such large feature changes are unlikely to be resolved, so closing.
