### ISSUE TITLE
What if forked Tables had a param that pointed to their parent?

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#584]
Random thought I had recently. `Table`s could have a `parent` param that pointed to the `Table` they forked from or `None` if it was a top-level table.

Ideally, top-level `Table`s would hold original untouched data and each child `Table` would be a different piece of analysis branched from it. We'd then be able to implement methods to display where a `Table` came from and how it goes back to the original data. This may slightly address the problem @livlab brought up in #573 and contribute to agate's focus on reproducibility. 

Not sure if this is worth implementing or if it steps on [proof's](https://github.com/wireservice/proof) feet. Wanted to note it down just in case.

**Comment by onyxfish** [comment]
So, an earlier version of agate actually did this. I do think it's a cool feature. The problem it causes is that from the perspective of the Python garbage collector, this basically means that every table you ever create exists forever. That can be a major performance drag. Now, agate doesn't optimize for performance as a rule, in this case I couldn't up with a compelling enough use-case to justify the overhead.

I'd be willing to revisit this if somebody has a killer use-case.

**Comment by nbedi** [comment]
Hm interesting. I guess in terms of garbage collection a table could instead reference just the very top-level parent Table so gc can deallocate Tables that should no longer be in memory. Then the table could also store a list of functions to go from parent to current and each new Table would build on the previous Table's list of functions. That sounds more like proof though (although I haven't dug into proof too much, mostly referencing my vague understanding of it). 

(I still don't have a killer use-case though, just a cool feature atm)

**Comment by onyxfish** [comment]
Yeah that does veer a lot closer to what proof does. The good thing about having this happen at the code level, like proof does, is that then the code is clearly the documentation of the process, rather then relying on the relationships between tables to be self-documenting. (Though I suppose you could serialize the method that generated the new table, but that get's pretty complicated.)

**Comment by nbedi** [comment]
Closing until a serious use case comes up.
