### ISSUE TITLE
It would be cool if we could open a fixed-width file using an ffs style config

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#585]
Maybe something like this

```python
Table.from_csv(fixed_path, fixed_width_format="./myconfig.csv")
```

Though that kwarg is kind of weird. Maybe something like this would be better?

```python
Table.from_fixed_width(fixed_path, format="./myconfig.csv")
```

Or maybe something totally different. But something that solved this would be great.

**Comment by nbedi** [comment]
Dupe of #358?

**Comment by onyxfish** [comment]
Yep, dupe. On the TODO list.
