### ISSUE TITLE
MemoryError when I open a 300MB file

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#586]
Hey,

I'm getting a ``MemoryError`` when I open a file of about 300 MB, even if I set the ``sniff_limit`` to low number like this.

```python
Table.from_csv("./my_big_file.csv", sniff_limit=1)
```

Am I doing something wrong, or is this just a limitation of agate?

**Comment by nbedi** [comment]
Try setting column types to a custom TypeTester with a low `limit` param. I've never actually tried a file that large so it may be a limitation. @onyxfish may be more helpful.

**Comment by onyxfish** [comment]
My hopes are low for a 300MB file working. Performance is highly dependent on the width and specific types of the data, but that's def way beyond any use case I've planned for. Would welcome any performance patches if you can pin down any specific thing that's slowing it up, though I suspect it's simply too much data to handle efficiently with Python's native types.

**Comment by palewire** [comment]
Obviously limitations are what they are. That's life.

But if this very common newsroom use case is a strict "no go" I think it
would be in the best interests of the user to be more explicit about
agate's limitations.

As a user who routinely is grips files of this size (yesterday it was
California's voter registration roll) I can testify that is frustrating to
have any tool advertised as a catch-all data solution only to be
immediately bogged down for reasons that aren't clear.

One potential fix that comes to mind is the warning github broadcasts when
you try to push large files, which culminates in a hard error over a
certain size (50MB?).

What if agate spit out a console warning if you try to open a file above a
certain size? It could even link to a longer explanation of agate's
limitations that would explain the reasons and point users to alternatives.
