### ISSUE TITLE
Extension: agate-feather

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#588]
Just read this. Curious if it could fit in with agate somehow. http://blog.rstudio.org/2016/03/29/feather/

**Comment by onyxfish** [comment]
Indeed: https://twitter.com/onyxfish/status/714908538460504064

It could also potentially provide a bridge for interoperability with pandas. Probably as an extension though. Unless it gets a huge amount of traction I won't put it in core.

**Comment by palewire** [comment]
Cool. I don't know enough about it to have any kind of opinion, but as an agate supporter one of my concerns is that be able to match pandas and other libraries in speed when handling large data files. You think this could help somehow?

**Comment by onyxfish** [comment]
Feather won't help that since it's aimed at serialization. More to the point though, agate is [explicitly designed](http://agate.readthedocs.org/en/1.3.0/contributing.html#principles) with the expectation that it will always be slower than pandas/R/etc. That's the cost of having a clean, dependency-free API.

**Comment by palewire** [comment]
Okie doke. That all makes sense, though I guess what my heart was stretching for here was some way that perhaps a user could opt-in to a meatier backend that could provide something like a turbo boost for big data sets without having to lose the agate API.

**Comment by onyxfish** [comment]
There were some experiments last year with alternative C backends, but the only one out there that's fully-baked is numpy, which completely upends agate's flexible type system. If somebody really wants to implement Cython backend for agate, I'd be totally onboard with figuring out how to make that pluggable.

**Comment by onyxfish** [comment]
I should note that I don't actually think what I just described is possible. High-speed performance and flexible variable typing/sizing are pretty fundamentally at odds.

**Comment by palewire** [comment]
K. Interesting food for thought. While it obviously should follow all the core goals of your project, I think that sort of thing would be an excellent add-on that would answer an easy to imagine critique and also serve as an attraction to convert users of the incumbent tools.

**Comment by jpmckinney** [comment]
Closing as no bandwidth.
