### ISSUE TITLE
CastError should specify the row and column where the error occurred

### ISSUE THREAD

**Issue by lexieheinle** [wireservice/agate#593]
I have some [data with tons of columns](https://github.com/lexieheinle/jour407homework/blob/master/StormData/nebraska-storm-analysis.ipynb), and I need to override several columns due to cast errors. However, it's difficult to narrow down which column is producing the data type error. Is it possible to print out the column name in addition to giving which value is producing the cast error?

**Comment by onyxfish** [comment]
This isn't possible now, but it's a great suggestion. We print the row and column in which the data appears.
