### ISSUE TITLE
Parse negative dollar amounts as number, not text

### ISSUE THREAD

**Issue by lindzcook** [wireservice/agate#595]
If a cell has "$1,287" it is parsed as a number, but if it has "-$1,287" it is parsed as text. Trying to force it to parse as a number throws the following: CastError: Can not parse value "-$1,287" as Decimal.

**Comment by onyxfish** [comment]
Huh yeah, that's a funny one we haven't hit before. Flagging as a bug. Thanks for reporting!

**Comment by nbedi** [comment]
Pushed a quick fix for that. Should be good in next release!
