### ISSUE TITLE
Cookbook: Top N percent

### ISSUE THREAD

**Issue by lindzcook** [wireservice/agate#603]
Under the [filter](https://agate.readthedocs.org/en/1.3.1/cookbook/filter.html) section, in the section N percent, is the following code:

```
percentiles = table.aggregate(agate.Percentiles('salary'])
top_ten_percent = table.where(lambda r: r['salary'] >= percentiles[90])
```

There is a typo where it is missing a bracket in the first line.

Additionally, the code results in the following error: 

'type' object is not subscriptable

You can see that with the following: 

```
rows = [
    dict(letter='a', number=1),
    dict(letter='b', number=2),
    dict(letter='c', number=3),
    dict(letter='c', number=4),
    dict(letter='c', number=5)
]

table = agate.Table.from_object(rows)
percentiles = table.aggregate(agate.Percentiles['number'])
top_ten_percent = table.where(lambda r: r['number'] >= percentiles[90])

```
Assuming this is a documentation problem...

**Comment by nbedi** [comment]
Thanks for catching this. Seems like the bracket should actually be a parenthesis:

`percentiles = table.aggregate(agate.Percentiles('number'))`

I can't test until later but let me know if that fixes things.

**Comment by lindzcook** [comment]
Yes that fixes it! Thanks.
