### ISSUE TITLE
Rewrite the agate tutorial as a Jupyter notebook

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#604]
After seeing [this](http://buzzfeednews.github.io/2016-04-federal-surveillance-planes/analysis.html) today it seems obvious to me now that the agate tutorial should simply be a Jupyter notebook. In addition to being more readable, it'll also benefit from being easier to test/sync when we change things and it pushes people in the direction of tools they should probably be using anyway.

**Comment by nbedi** [comment]
:+1:

**Comment by onyxfish** [comment]
Hmmm, big disadvantage to doing this: losing automatic API doc links.

**Comment by nbedi** [comment]
Could converting to rst on building docs somehow help that? Something like hooking `ipython nbconvert --to rst` to the build process.
