### ISSUE TITLE
TypeError: 'TypeTester' object is not iterable

### ISSUE THREAD

**Issue by rausnitz** [wireservice/agate#609]
I'm trying to get the [tutorial](http://agate.readthedocs.io/en/1.3.1/tutorial.html) to work on my laptop (Ubuntu 14.04 and Python 2.7.6) and hitting an error early on that I can't seem to debug. I haven't been able to find another example of this issue.

Here's what I've got in a file called `agate_test.py`, referencing the example CSV from the tutorial.
```
import agate

tester = agate.TypeTester(limit=100)

exonerations = agate.Table.from_csv('exonerations-20150828.csv', tester)
```
Then I run the command `python agate_test.py` and get this message:

```
Traceback (most recent call last):
  File "agate_test.py", line 5, in <module>
    exonerations = agate.Table.from_csv('exonerations-20150828.csv', tester)
  File "/usr/local/lib/python2.7/dist-packages/agate/table/__init__.py", line 372, in from_csv
    return Table(rows, column_names, column_types, row_names=row_names)
  File "/usr/local/lib/python2.7/dist-packages/agate/table/__init__.py", line 102, in __init__
    for i, column_name in enumerate(column_names):
TypeError: 'TypeTester' object is not iterable
```
I get the same problem with other CSV files as well.

**Comment by nbedi** [comment]
Thanks for submitting this issue. Could you try replacing the tester argument in the last line with `column_types=tester`? It should look like this:

`exonerations = agate.Table.from_csv('exonerations-20150828.csv', column_types=tester)`

Let me know if that does/doesn't solve the issue.

**Comment by rausnitz** [comment]
Issue solved. Thank you!

**Comment by nbedi** [comment]
Cool, fixed the typo in the tutorial, thanks for catching it!
