### ISSUE TITLE
Behavior of slugify and renaming of duplicate columns seems inconsistent

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#615]
See test `test_rename_slugify_columns_in_place`

Not sure what to do about this. Should probably revisit what happens to dupe column names.

**Comment by nbedi** [comment]
Since we're reimplementing, we should probably make this consistent.

Renaming turns duplicates into `dup` and `dup_2`.

Slug turns duplicates into `dup` and `dup-1`.

I think we should stick with renaming's format since it's been around for longer but open to either. Thoughts @onyxfish?

**Comment by onyxfish** [comment]
I agree—both for the reason you give, but also because dashes as column names are just weird. (Not valid property names in most programming languages.)

**Comment by nbedi** [comment]
I'm not sure what to do in the case of slugifying column names in place though. 

Underscores are replaced with the separator in slugify and there's no way to absolutely tell if an underscore was used for deduping the original column names.

**Comment by nbedi** [comment]
Here's the reimplementation w/ consistent renaming for the most part:
https://github.com/wireservice/agate/tree/redo-slug

`test_rename_slugify_columns_in_place` is the same though.

**Comment by nbedi** [comment]
@onyxfish Looking at this again, we could just make the default separator for `slugify` an underscore instead of a dash. It breaks what's in the current version but totally smooths over all the inconsistencies.

**Comment by onyxfish** [comment]
Love it. Closing out.

**Comment by nbedi** [comment]
I just thought of another edge case... I'll open an issue. Sorry this functionality has been a bundle of edge cases.
