### ISSUE TITLE
Slug should accept non-Text columns

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#618]

**Comment by nbedi** [comment]
I'm not quite sure how other datatypes would be slugged/standardized. Can you show me an example of what you're thinking for the other types? Thanks!

**Comment by onyxfish** [comment]
I'm not sure either! This came up because I was working on something else and the output was weird, but now I'm having trouble remembering what it was...

**Comment by jpmckinney** [comment]
Closing, since the issue can't be remembered.
