### ISSUE TITLE
Fixed reader should support 1-base indexing and `end` column (rather than length)

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#621]
Right now it's too much a pain to convert schema's from SASS, SPSS, etc.

**Comment by onyxfish** [comment]
`base_one=None` -> Infer (default)
`base_one=True` -> Force base one parsing
`base_one=False` -> Force base zero parsing

**Comment by jpmckinney** [comment]
Closing as there is no other expressed demand for this feature.
