### ISSUE TITLE
to_csv encoding problem?

### ISSUE THREAD

**Issue by tf13** [wireservice/agate#624]
I'm getting a UnicodeEncodeError when I try to send a table to_csv. The table was made with a join of two other tables, both loaded from csv using utf-8 encoding. The character that seems to have caused the error is apparently just an en-dash -- nothing too exotic. Not sure if I'm doing something wrong or if something worse is going on.

The traceback:

```
Traceback (most recent call last):
  File "path/goes/here/lobbyists.py", line 57, in <module>
    combo.to_csv('combo.csv')
  File "/Users/theofrancis/miniconda3/lib/python3.5/site-packages/agate/table/__init__.py", line 408, in to_csv
    writer.writerow(tuple(csv_funcs[i](d) for i, d in enumerate(row)))
  File "/Users/theofrancis/miniconda3/lib/python3.5/site-packages/agate/csv_py3.py", line 91, in writerow
    self.writer.writerow(row)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 282: ordinal not in range(128)

```

**Comment by onyxfish** [comment]
Hey @tf13, that sounds like a bug. Can you provide the files (or subsets of the files) that created the error?

**Comment by nbedi** [comment]
Probably related to this: https://github.com/wireservice/csvkit/issues/596. And maybe related to this: https://github.com/wireservice/csvkit/issues/631. 

Will try to take a look this week.

**Comment by nbedi** [comment]
@tf13 I do need the files that created the error to look further into this

**Comment by jpmckinney** [comment]
Note that the csvkit issues were resolved, so this is likely resolved.

**Comment by tf13** [comment]
Hi. I'm still/again having this problem. If there's a way to send an extract of the data, I have an 8-row sample file that chokes on an É (u'\xc9') when I try table.to_csv('filename.csv'), with the following:

> UnicodeEncodeError: 'ascii' codec can't encode character '\xc9' in position 34: ordinal not in range(128)

I'm using agate 1.5.5 and Python 3.4.5 (in Pyzo 4.3.1, if that's relevant). Happy to send the sample data privately (<1KB).

**Comment by JDFagan** [comment]
I have same issue.  Can we add to_csv to accept an encoding parameter so we can override?  It always seems to default as ascii despite my system being utf-8 default.  See https://github.com/wireservice/agate/issues/677

**Comment by tf13** [comment]
FWIW, I think I traced my issue to a locale problem -- for some reason, the csv writer looks at my locale, and decides I should be using ascii. Passing an encoding parameter, as JDFagan suggests, would prevent this.

**Comment by bitlather** [comment]
This was among the top results when I was looking up the error:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)

I thought I'd show how I fixed it for anyone else who ends up here.

### Replicating The Problem

Consider this script:

```
import csv

data = [["a", "b", u'\xe9']]

with open("output.csv", "w") as csv_file:
    writer = csv.writer(csv_file, quoting=csv.QUOTE_ALL)
    writer.writerows(data)
```

When I run it, I get:

```
$ python tmp_csv_script.py 
Traceback (most recent call last):
  File "tmp_csv_script.py", line 7, in <module>
    writer.writerows(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)
```

### Solution

Set default encoding to utf8.

```
import csv

import sys
reload(sys)
sys.setdefaultencoding('utf8')

data = [["a", "b", u'\xe9']]

with open("output.csv", "w") as csv_file:
    writer = csv.writer(csv_file, quoting=csv.QUOTE_ALL)
    writer.writerows(data)
```

Running this was successful for me, and the output looked like this:

```
"a","b","é"
```

### Further Reading

There is an excellent blog article that might be able to help you out more, if you don't want to set the default encoding:

[Python: UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 11: ordinal not in range(128)](https://markhneedham.com/blog/2015/05/21/python-unicodeencodeerror-ascii-codec-cant-encode-character-uxfc-in-position-11-ordinal-not-in-range128/)

**Comment by jpmckinney** [comment]
Noting that this might help solve some of the encoding issues on Windows prior to Python 3.8 (currently skipped in CI).

**Comment by jpmckinney** [comment]
I'm not sure that this still occurs on Windows with Python 3.8+. Closing until anyone reports otherwise.
