### ISSUE TITLE
Flag for rendering Markdown-friendly tables?

### ISSUE THREAD

**Issue by brentajones** [wireservice/agate#626]
Not sure if this is a feature that would be useful to many. There have been a few occasions where I'd like the output of csvlook to be a Multi-Markdown table. It's very close to being compatible as it is.

Here are the changes I just made to a very simple table to change from csvlook output to make a Markdown-friendly table:
- Remove top and bottom "frame" rows (the pipe, dashes and plus signs on the first and last line).
- Remove pipes at beginning and end of lines
- Change plus signs in separator rows to pipes

_[previously suggested over on csvkit](https://github.com/wireservice/csvkit/issues/620), @jpmckinney said it's rendered from here_

**Comment by nbedi** [comment]
I'll defer this to @onyxfish. Seems reasonable but this will open the door to supporting other table formats as well (although we already support HTML). 

I'm not actually sure why the tables are currently formatted the way they are. If there is no particular reason, and a Markdown-friendly table isn't much different, maybe the default should just be Markdown-friendly.

**Comment by onyxfish** [comment]
I don't disagree nor do I have a counterargument. Let's change it!
