### ISSUE TITLE
Is utf-8 hardcoded?

### ISSUE THREAD

**Issue by TimMurnaghan** [wireservice/agate#635]
$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 34, in <module>
    main()
  File "./test.py", line 18, in main
    lineitems = agate.Table.from_csv('in.csv')
  File "C:\Users\Tim\Anaconda2\lib\site-packages\agate\table\from_csv.py", line 69, in from_csv
    f = six.StringIO(f.read().encode('utf-8'))
  File "C:\Users\Tim\Anaconda2\lib\codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 569372: invalid start byte

Is there a way of using the system encoding (which I can set to iso-8859-1) or let us pass it in to the reader?

This is pretty essential to usability on Windows are we're going to get a variety of encodings on csv files - and it's a bit of barrier to entry if you get arcane failures at the first step.

**Comment by nbedi** [comment]
Hi Tim, `Table.from_csv` does have an encoding argument to pass a specific encoding: http://agate.readthedocs.io/en/1.4.0/api/table.html#agate.Table.from_csv.

If there is still an issue, can you paste in the script you're running and a bit of the data causing an issue?

**Comment by onyxfish** [comment]
Hi Tim, it's hard to tell at a glance if you've found a bug or just a configuration issue. However, what I can say is that hard-coded variable only affects how the data is represented internally to agate. (Everything gets processed as unicode for consistency.) I suspect that Neil's suggestion about using the `encoding` parameter is all you need, however, given that this is Python 2 on Windows (a combination I've rarely, if ever, tested) it's plausible there is another bug here. Please let us know if you keep having problems?

**Comment by TimMurnaghan** [comment]
@nbedi @onyxfish. Here's what that link says.

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

I haven't been able to find documentation about that parameter as there's no mention in the 1.3 docs that are online.  It's hard to package this up to make it reproducible. What I did in the end was make the csv file UTF-8 by a nasty process involving notepad++ which is one of the few tools which tells you what it's doing w.r.t. to encoding.

**Comment by nbedi** [comment]
Sorry about that, I think there's a caching issue or something with the docs. Generally a few hard refreshes fixes that. This specific documentation is also in the code: https://github.com/wireservice/agate/blob/master/agate/table/from_csv.py#L36.

I can close this for now and reopen if you run into another encoding issue. Thanks for opening the issue!
