### ISSUE TITLE
GPLv3 dependency

### ISSUE THREAD

**Issue by Jenselme** [wireservice/agate#660]
Hi,

In order to update [csvkit](https://github.com/wireservice/csvkit) to 1.0.1 in fedora, I am in the process of packaging agate. During this process, I found that it relies on a GPLv3 dependency [awesome-slugify](https://github.com/dimka665/awesome-slugify) (cf [awesome-slugify](https://github.com/dimka665/awesome-slugify/blob/master/setup.py#L22)) while being licensed on the MIT license.

As far a I know, this means that agate needs to be license under GPLv3.

Possible solutions:
- Switch to another lib to create slug.  Eg [python-slugify](https://github.com/un33k/python-slugify) (doesn't support unique slugs though)
- Make awesome-slugify change their license. There is an on going discussion about this [here](https://github.com/dimka665/awesome-slugify/issues/24). It is currently released under GPLv3 because one of its dependencies is GPLv2+. Some are asking the maintainer to switch to something else.

**Comment by nbedi** [comment]
Great catch.

@onyxfish it seems like awesome-slugify is causing a bunch of issues with agate and csvkit (some closed, some not). Should we work on a switch to python-slugify and implement unique slug functionality on top of it? (python-slugify may cause its own set of issues but the awesome-slugify licensing seems like a road block).

**Comment by onyxfish** [comment]
Just seeing this, thanks for pointing it out! We certainly want to fix this as quickly as we can. @nbedi I agree with your plan. I think we should switch to python-slugify and then write a little bit of logic on  top that implements the deduping logic for unique slugs.

**Comment by onyxfish** [comment]
This is finally done! Thanks again for flagging and sorry it took me so long.

**Comment by Jenselme** [comment]
@onyxfish No problem. Thanks for the work! I can resume my packaging them!
