### ISSUE TITLE
Reading xlsx files containing numbers in the first row

### ISSUE THREAD

**Issue by Fil** [wireservice/agate#664]
Hello,

I have a whole bunch of xlsx files that contain names and dates on the first row, and would like to import them with in2csv; however I get this error from agate:

`Column names must be strings or None.`

In this case I'd need agate to create column names based on the date/number, rather than crash.

test case:
```
A	2017
A	B
```

**Comment by Fil** [comment]
fwiw I have patched like this in table.py, instead of raising the error:
```
new_column_name = '%s' % str(column_name)
```

**Comment by nbedi** [comment]
I like that change. Seems better for usability. @onyxfish Am I missing an issue this could cause?

**Comment by onyxfish** [comment]
Closing since this has been merged elsewhere.
