### ISSUE TITLE
Limit slugify separator to non-alphanumeric characters

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#673]
If you use an alphanumberic separator, you won't be able to later change the separator with `Table.rename`.

**Comment by onyxfish** [comment]
I don't quite follow. Can you spell this out for me?

**Comment by nbedi** [comment]
Yes, sorry about that. Slugify modules replace non-alphanumeric characters with a given separator so 'abc de*f' -> 'abc_de_f'.

I gave users the ability to choose their separator using kwargs in `Table.rename`. But if users choose an alphanumeric character like '0' ('abc de*f' -> 'abc0de0f'), they would not be able to replace those separators with the same argument. 

They could technically with a smart rename, but it might just be worth it to be opinionated and say separators are non-alphanumeric (although I'm open to other thoughts).

**Comment by onyxfish** [comment]
Hmmm, this feels like user error to me. I can imagine a case where somebody might want to use an alphanumeric separator and preventing them from doing that because they *also* might want to rename the column feels a little arbitrary, no?

**Comment by nbedi** [comment]
Yes that's fair and something I was thinking about. I may be falling way too deep in this slugify code. Let's close this! Thanks for cutting me off.

**Comment by onyxfish** [comment]
💯 for talking it out.
