### ISSUE TITLE
BOM question

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#688]
Hello!

I am working on a [small Python library](https://github.com/datadesk/python-censusbatchgeocoder) that uses agate's handy csv reader and writer methods internally to handle data files. I've run into an edge case and I wonder if you can help me with it.

It has to do with our old buddy, the Windows BOM. Sometimes, files will start with it and then ``\ufeff`` will appear on the first header's key when using ``agate.csv.DictReader``. 

The unicodecsv library appear to handle this issue if you do something like this:

```python
unicodecsv.DictReader(open("./data.csv", 'r'), encoding="utf-8-sig")
```

Does agate offer some similar solution, or something else I can do or offer to my module's users to help them work through this kind of thing?

**Comment by palewire** [comment]
Great Scott!

```agate
agate.csv.DictReader(open("./data.csv", 'r'), encoding="utf-8-sig")
```

I think I can self own and close this one myself. 

Hey small thing from [your docs](http://agate.readthedocs.io/en/1.6.0/api/csv.html). The page on the csv tools suggests ```import agate as csv```. But if I do that here's what happens.

```python
>>> import agate as csv
>>> csv.DictReader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'DictReader'
```

So should the advice change a little to maybe be:

```python
>>> import agate as csv
```

**Comment by palewire** [comment]
Or is the ``encoding`` thing above only going to work in Python 2. The BOM has me spun around guys. I'm lost.

**Comment by nbedi** [comment]
I haven't had a chance to look too hard at this but would opening the file with an encoding argument solve this? Search "encoding" on this page for what I'm thinking: https://docs.python.org/3/library/csv.html. 

I'm not as familiar with BOM issues so I may be completely off here.

**Comment by palewire** [comment]
Hey. That's seemed to work!. At least in my crappy unittest. Thanks for the tip. If you're interested, I'm using agate's CSV reading helpers in the guts of [a new geocoding library](https://github.com/datadesk/python-censusbatchgeocoder/blob/master/censusbatchgeocoder/__init__.py). I'm sure there are ways to improve (or rip up and start over) on how I'm handing the different inputs in the two different version of Python. If you have any thoughts I'd love to hear them.

**Comment by nbedi** [comment]
Ooo I'll take a look and send it around here. Thanks for sharing!

**Comment by palewire** [comment]
I'm sure I'm screwing something up.
