### ISSUE TITLE
The link for the agate readthedocs Tutorial site has a broken link

### ISSUE THREAD

**Issue by dbfreem** [wireservice/agate#701]
On the [agate readthedocs site](http://agate.readthedocs.io/en/1.6.0/tutorial.html) the link to the tutorial leads to https://github.com/wireservice/agate/blob/1.5.6/tutorial.ipynb instead of the 1.6.0 link

**Comment by nbedi** [comment]
Dup of https://github.com/wireservice/agate/issues/682. Will be fixed in the next release. Thanks for reporting.
