### ISSUE TITLE
Relaxing type_tester `force` argument from raising an exception when column name doesn't exist

### ISSUE THREAD

**Issue by Mr-F** [wireservice/agate#704]
I have a large number of column type definitions which commonly contain null values but should be numeric values.  However, Agate seems to default to a `Boolean` column type.

I set up a type_tester bit due to the larger number of columns and the various different table structures thought I could just define one list of column names to type mappings which could simply be used.  However, looking into the code it seems that if the column name isn't found then it raises an error.

Could this restriction be either relaxed and not raise an exception, or alternatively a new keyword argument be added to allow users to provide a complete list, which will simply apply if the column exists, and ignore if it's not?

If it helps I can take a look at making the required changes and submitting a pull request.  Just wasn't sure what you view of which would be the most appropriate way to keep it within your view for the library

**Comment by Kirkman** [comment]
I want to second this.  It would be extremely helpful if Agate didn't throw an exception here.  If Agate loads a CSV and doesn't find a column I've specified in `force`, I want Agate to ignore it and just keep processing.

**Comment by jpmckinney** [comment]
Re: defaulting to boolean, see #371

**Comment by jpmckinney** [comment]
> If it helps I can take a look at making the required changes and submitting a pull request. Just wasn't sure what you view of which would be the most appropriate way to keep it within your view for the library

In case anyone depends on the current error behavior (e.g. it's a good way to catch typos), I prefer a new keyword argument to ignore and continue.

**Comment by jpmckinney** [comment]
Need to review #747

**Comment by jpmckinney** [comment]
Closed by #747.
