### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by Mr-F** [wireservice/agate#707]
When calculating the Mean of a column I came across a situation where it would generate an error of divide by zero.  I couldn't see anything in the documentation about this so have created a small pull request which addresses this.

The solution I've implemented is to return None from the mean operation if there are no valid values.  Otherwise, the calculation proceeds as normal

https://github.com/wireservice/agate/pull/706

Happy to discuss and amend if you feel that a different solution would be better.  But thought it better to provide a solution rather than simply keep raising issues.

**Comment by jpmckinney** [comment]
Fixed by #706
