### ISSUE TITLE
Broken link to tutorial in the docs

### ISSUE THREAD

**Issue by simonw** [wireservice/agate#708]
On this page: http://agate.readthedocs.io/en/1.6.0/tutorial.html

The "Find it on GitHub" link goes to https://github.com/wireservice/agate/blob/1.5.6/tutorial.ipynb which is a 404

It should go to https://github.com/wireservice/agate/blob/master/tutorial.ipynb

**Comment by simonw** [comment]
Or maybe it should go to https://github.com/wireservice/agate/blob/master/tutorial.ipynb

**Comment by nbedi** [comment]
Thanks for opening this. It's been fixed for the next release. Dup of https://github.com/wireservice/agate/issues/682.
