### ISSUE TITLE
Annual release cycle?

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/agate#711]
I'm thinking of releasing csvkit once a year (April 28), but some bug fixes require a release of agate. Want to commit to an annual release of agate (February 28)?

**Comment by ghisvail** [comment]
What about [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often) instead? Your users would benefit more from a constant roll-out of fixes, rather than wait the next yearly milestone.

**Comment by jpmckinney** [comment]
Capacity is the issue. Also, these two projects don't change so frequently.

**Comment by Mr-F** [comment]
@ghisvail has a point on this one.  Can I ask when you say "capacity is the issue" do you mean your physical time to deal with pull requests and then make a release?  Is there any mileage in looking to put together a core group of members that wouldn't mind helping out with making releases.  The list of contributors is quite large, but I don't know how many of them are still actively involved.  

Just a thought

**Comment by ghisvail** [comment]
@jpmckinney Not sure what you mean by capacity. With CI and a fairly comprehensive test suite already in place, you have got everything in place to enable frequent releases. Is tagging the source tree and pushing to pypi so expensive these days?

**Comment by jpmckinney** [comment]
Releases aren't free. There tend to be more support requests and issues created after a release; so lowering the number of releases reduces the total hours spent on such tasks. csvkit and agate typically can't be released without all agate dependencies being at least reviewed for release; lowering the number of releases reduces the total hours spent doing review across repositories. RERO works when there is a active development team that can, for example, rescue a bad release with a quick bugfix. This is not the situation here.

**Comment by jpmckinney** [comment]
@Mr-F Making releases is not the expensive part of maintaining these repositories. We have not yet found contributors willing to triage issues, etc. I'm not the original maintainer, and that maintainer spent a long time actively seeking co-maintainers, before I proactively started contributing. I'm not sure there are simple solutions here.

**Comment by nbedi** [comment]
Just chiming in to say I agree with @jpmckinney on all of these points. An annual release cycle will also get releases out consistently, rather than letting things slow to a complete stop.

**Comment by jpmckinney** [comment]
@nbedi Is there anything more you need to get into 1.6.1, or is it ready for release?

**Comment by nbedi** [comment]
@jpmckinney I'm sorry for the lack of responses, the day job has been pretty crazy for a while. Pretty sure 1.6.1 is ready for a release. There are a few more reported bugs but the release doesn't need to be held up for them. Do you have release access? I do not unfortunately.

**Comment by jpmckinney** [comment]
1.6.1 released!
