### ISSUE TITLE
Test failure in test_print_bars_with_nulls

### ISSUE THREAD

**Issue by ghisvail** [wireservice/agate#712]
The Debian reproducible testers reported the following error when running the test suite:
```
======================================================================
FAIL: test_print_bars_with_nulls (tests.test_table.test_print_bars.TestPrintBars)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-agate-1.6.0/2nd/.pybuild/pythonX.Y_3.6/build/tests/test_table/test_print_bars.py", line 100, in test_print_bars_with_nulls
    self.assertEqual(output.getvalue(), "three   two\n"
AssertionError: 'three   two\na     2\xa0000 |:::::::\nNone      - |       \nc[64 chars]00\n' != 'three   two\na     2,000 |:::::::\nNone      - |       \nc   [58 chars]00\n'
  three   two
- a     2 000 |:::::::
?        ^
+ a     2,000 |:::::::
?        ^
  None      - |       
  c         1 |       
              +------+
-             0  2 000
?                 ^
+             0  2,000
?                 ^
```

For each tested architecture, the first build succeeds but the second fails:
amd64: [build1](https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/python-agate_1.6.0-3.rbuild.log) [build2](https://tests.reproducible-builds.org/debian/logs/unstable/amd64/python-agate_1.6.0-3.build2.log.gz)
i386: [build1](https://tests.reproducible-builds.org/debian/rbuild/unstable/i386/python-agate_1.6.0-3.rbuild.log) [build2](https://tests.reproducible-builds.org/debian/logs/unstable/i386/python-agate_1.6.0-3.build2.log.gz)
arm64: [build1](https://tests.reproducible-builds.org/debian/rbuild/unstable/arm64/python-agate_1.6.0-3.rbuild.log) [build2](https://tests.reproducible-builds.org/debian/logs/unstable/arm64/python-agate_1.6.0-3.build2.log.gz)
armhf: [build1](https://tests.reproducible-builds.org/debian/rbuild/unstable/armhf/python-agate_1.6.0-3.rbuild.log) [build2](https://tests.reproducible-builds.org/debian/logs/unstable/armhf/python-agate_1.6.0-3.build2.log.gz)

**Comment by cmosig** [comment]
Same problem on Manjaro Linux.

**Comment by alerque** [comment]
This appears to be the same problem I just came here to report [from the Arch Linux bulids](https://aur.archlinux.org/packages/python-agate/#news), namely that the test suite fails when run on any system locale that uses different thousand or decimal place separators. I think the test suite needs to define the locale it wants to use as the one used to generated the expected output before running otherwise it may not match.

**Comment by jpmckinney** [comment]
This should now be fixed on HEAD. New release coming shortly.
