### ISSUE TITLE
TypeError when re.match hits null

### ISSUE THREAD

**Issue by golfecholima** [wireservice/agate#715]
When

`re.match('^TEMPORARY (?!SPACE)', row['PURPOSE']))`

Hits a null value this error happens ...

`TypeError: expected string or bytes-like object`

Seems like it should skip it. Totally possible I'm doing something wrong too. But filling the empty cell cures the problem.

**Comment by jpmckinney** [comment]
Hi @golfecholima, `re.match` is provided by Python, not agate. That said, you can do `str(row['Purpose'])` to guarantee that `re.match` is given a string.

**Comment by golfecholima** [comment]
Ha, wow ... My Python has come a ways since posting this. Thank you!
