### ISSUE TITLE
Best way to assert two agate tables are the same

### ISSUE THREAD

**Issue by halloleo** [wireservice/agate#718]
How do I best test whether two agate tables have the same cells? Is there a function for this in the agate package?

**Comment by jpmckinney** [comment]
If you want to test that the rows are the same:

```python
from agate import Table
Table([[1,2,3]]).rows == Table([[1,2,3]]).rows  # True
```

To check both rows and columns:

```python
Table([[1,2,3]]).rows == Table([[1,2,3]]).rows and Table([[1,2,3]]).columns == Table([[1,2,3]]).columns
```

**Comment by halloleo** [comment]
Thanks @jpmckinney. Makes sense. Will keep it in mind when I use agate again. :-)
