### ISSUE TITLE
Is it possible to pass variables to an Agate.Formula()?

### ISSUE THREAD

**Issue by Kirkman** [wireservice/agate#722]
As far as I can tell, there's no way to pass a variable to a custom Agate.Formula(), right? 

I know I can do this, and `x_y_to_lat_lng()` will receive a `row` variable:
```
    new_table = new_table.compute([
        ('coordinates', agate.Formula( text_type, x_y_to_lat_lng )),
    ])
```

But is there a way to do the equivalent of something like this?

```
    new_table = new_table.compute([
        ('coordinates', agate.Formula( text_type, x_y_to_lat_lng(geojson) )),
    ])
```

I'd like to load a file once and pass its data to the `x_y_to_lat_lng()` function. But all I can figure out how to do is to load the file _within_ the function, which means loading it thousands of times as I process all the rows in a table.

**Comment by lcorbasson** [comment]
Load your file once, mapping your geojson information to the coordinates you'll encounter in the table; e.g. as a dict.
Then use:

    new_table = new_table.compute([
        ('coordinates', agate.Formula( text_type, lambda row: x_y_to_lat_lng(row['x_y']) )),
    ])

Or even:

    new_table = new_table.compute([
        ('coordinates', agate.Formula( text_type, lambda row: x_y_to_lat_lng[row['x_y'])] ),
    ])

if `x_y_to_lat_lng` can be a dict.

**Comment by jpmckinney** [comment]
Thanks for answering, @lcorbasson !
