### ISSUE TITLE
How work with composite id in Table.Join?

### ISSUE THREAD

**Issue by PedroHFranco** [wireservice/agate#727]
Hello,
I'm trying to use a composite id in Table.Join, 
I'm pass the both key in left and right sides, 

```
jointab = tables[0]
testea = [3,5]
testeb = [8,1]
jointab = agate.Table.join(jointab, table, testea, testeb)
```

And i'm gotting this error

> tuple.index(x): x not in tuple

Has an way to work with composite id?
Thanks.

**Comment by lcorbasson** [comment]
You should use:

    jointab = jointab.join(table, testea, testeb)
