### ISSUE TITLE
Dependency bug in Parsedatetime v2.5 causing Agate / CSVKit issues

### ISSUE THREAD

**Issue by steve-estes** [wireservice/agate#743]
So in trying to use csvkit's in2csv tool (which relies on Agate tables), I recently got an error I hadn't seen before.  The table was unusual (106 columns, some of which had periods in their names) but not massively so.  The operation suddenly died with a:

`KeyError: 's'`

I traced this to this issue in another project:

https://github.com/dssg/triage/issues/721

Where they discovered that the problem was with parsedatetime v 2.5.  Updating that for me fixed the issue.  As agate currently requires >= 2.1, may I suggest that that dependency in requirements.txt either get updated to >= 2.6, or (if this can be specified) allow 2.1-2.4, or >=2.6.

**Comment by jpmckinney** [comment]
Thank you for reporting the issue!
