### ISSUE TITLE
Ah ha! It looks like you named your script `agate.py` which is also the name of the library, so instead of importing agate it's importing your own code. Try renaming your script!

### ISSUE THREAD

**Issue by AyushaSinha** [wireservice/agate#748]
Ah ha! It looks like you named your script `agate.py` which is also the name of the library, so instead of importing agate it's importing your own code. Try renaming your script!

_Originally posted by @onyxfish in https://github.com/wireservice/agate/issues/399#issuecomment-155896885_

**Comment by AyushaSinha** [comment]
My script name is not same lib name but then also am getting attribute error:
 Traceback (most recent call last):
  File "C:\Python\example.py", line 9, in <module>
    t = h.Table(table_dict)
AttributeError: module 'html' has no attribute 'Table'

Below is my code.:
import json
import html
from html.entities import html5 as _html5
table = [{'Results': "Pass", 'Test Name' : "Test Case Name 1" , 'Time Taken' : "12:34:02"}]
[{'Results': "Fail", 'Test Name' : "Test Case Name 2" , 'Time Taken' : "03:00:02"}]
table_dict = json.dumps(table)
print(table_dict)
h = html
t = h.Table(table_dict)
f = open('C:\\Users\\Aayus\\Documents\\Ayushacodetest.html', 'w')
f.write(str(t))
f.close()
print(t)

Please help me to get rid of this issue.

**Comment by jpmckinney** [comment]
You are importing some `html` package, which is not related to agate. I do not know that package, so cannot help.
