### ISSUE TITLE
PyICU dependency causing pip upgrade failure on macOS

### ISSUE THREAD

**Issue by anthonydb** [wireservice/agate#755]
Attempting to update to the latest version of agate causes an error on macOS:

`FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'`

I may be wrong, but after a bunch of reading, it looks like the culprit is the PyICU dependency, which, according to that library's author, cannot be pip installed:

https://github.com/ovalhub/pyicu/issues/141#issuecomment-797807893

**Comment by tommyjcarpenter** [comment]
this is a dupe of the issue I raised last week here: https://github.com/wireservice/agate/issues/754

**Comment by anthonydb** [comment]
Generates a different error on macOS even though it has the same issue at its root.

**Comment by palewire** [comment]
This also causes install errors far far far downstream on Heroku, where the PyICU library can't compile.

https://stackoverflow.com/questions/31975668/installation-of-pyicu-on-heroku

**Comment by palewire** [comment]
My hopes are not high for heroku after reading this https://gitlab.pyicu.org/main/pyicu/-/issues/150

**Comment by jpmckinney** [comment]
I've made a commit that removes the PyICU dependency. Let me know if it works, and I'll make a release.

**Comment by palewire** [comment]
I trust you on it. I say let it rip.

**Comment by tommyjcarpenter** [comment]
is there a PR to review?

**Comment by anthonydb** [comment]
I'm still getting this error on macOS with version 1.6.2. Do you need to also specify `darwin` for `sys_platform` in `setup.py`?

**Comment by jpmckinney** [comment]
It will be fixed in 1.6.3 only.
