### ISSUE TITLE
agate requires parsedatetime != 2.5 but won't allow 2.6

### ISSUE THREAD

**Issue by howff** [wireservice/agate#766]
Trying to install agate (1.6.3) it complains that `parsedatetime` must be `!=2.5  !=2.6  >=2.1` but according to #743 only 2.5 is the problem. Is there some reason why v2.6 is not allowed?

**Comment by jpmckinney** [comment]
It doesn't allow it due to https://github.com/bear/parsedatetime/pull/247. I suppose we can relax it now that we dropped Python 2.7.

**Comment by jakeberesford-palmetto** [comment]
It would be great to get this updated as `parsedatetime` v2.4 depends on `future`, which appears to be unmaintained and has a CVE https://github.com/PythonCharmers/python-future/pull/610 - that dependency is dropped in parsedatetime v2.5+

Relaxing this version pin will resolve a high-severity CVE in one of my projects.

**Comment by jpmckinney** [comment]
2.6 is now allowed in 1.7.1.
