### ISSUE TITLE
"/" separator for flat JSON files could not be unique

### ISSUE THREAD

**Issue by frafra** [wireservice/agate#767]
Hi,
I tried to use `a/b` as a key in a test JSON file, to see how agate would flatten it, since `/` is added when recursing JSON files. I see that agate keeps that original `/`, so the output can be misleading.
I would suggest having an option to replace the original `/` to avoid confusion,

**Comment by jpmckinney** [comment]
At a minimum, this behavior can be documented.

**Comment by jpmckinney** [comment]
I've documented it for now. I'm not sure that this sort of collision ever occurs in real data.

**Comment by frafra** [comment]
Thanks :) Well, it happened on my data 😄

**Comment by jpmckinney** [comment]
What were the colliding keys in your data?

**Comment by frafra** [comment]
All of them, because the original file has two lines of header, so they were processed into a single header line containing "/" as separator. Rather uncommon, I know :)

**Comment by jpmckinney** [comment]
Strange, can you paste the first few lines here?

**Comment by frafra** [comment]
Well, it has been a while ago and I moved forward. sorry :)
