### ISSUE TITLE
Feature request: line wrapping

### ISSUE THREAD

**Issue by jugglinmike** [wireservice/agate#773]
### Use case `#`1: data which includes newlines

Current behavior:

    $ printf 'a,b,c\nshort,short,"two\nlines"\nshort,short,short' | csvlook
    | a     | b     | c         |
    | ----- | ----- | --------- |
    | short | short | two
    lines |
    | short | short | short     |

Desired behavior:

    $ printf 'a,b,c\nshort,short,"two\nlines"\nshort,short,short' | csvlook
    | a     | b     | c         |
    | ----- | ----- | --------- |
    | short | short | two       |
    |                 lines     |
    | short | short | short     |

### Use case `#`2: insertion of newlines to improve readability

Current behavior:

    $ printf 'a,b,c\nshort,short,very very very very very very very very long\nshort,short,short' | csvlook
    | a     | b     | c                                            |
    | ----- | ----- | -------------------------------------------- |
    | short | short | very very very very very very very very long |
    | short | short | short                                        |

Desired behavior (with starperson `--wrap-at` flag):

    $ printf 'a,b,c\nshort,short,very very very very very very very very long\nshort,short,short' | csvlook --wrap-at 44
    | a     | b     | c                        |
    | ----- | ----- | ------------------------ |
    | short | short | very very very very very |
    |                 very very very long      |
    | short | short | short                    |

Relevant issue: gh-442. That documents requests for two separate features--wrapping and truncation--in this project and csvkit, but it was considered resolved with the introduction of truncation.

Thanks for maintaining a great tool!

**Comment by jpmckinney** [comment]
Duplicate #749. Can you try installing the PR #750 and seeing if it suits your needs?
