### ISSUE TITLE
Methods missing on some doc pages

### ISSUE THREAD

**Issue by Kirkman** [wireservice/agate#775]
I've noticed in recent months that methods are missing on various Agate documentation pages on ReadTheDocs in the `latest` set.

For example, compare `latest` with `1.7.1` on the API > Columns and Rows page:
* https://agate.readthedocs.io/en/latest/api/columns_and_rows.html
* https://agate.readthedocs.io/en/1.7.1/api/columns_and_rows.html

... Or on the API > Data types > Detailed list page:
* https://agate.readthedocs.io/en/latest/api/data_types.html#detailed-list
* https://agate.readthedocs.io/en/1.7.1/api/data_types.html#detailed-list

**Comment by jpmckinney** [comment]
Thanks for catching! Had to do with new Sphinx ignoring old configuration name.
