### ISSUE TITLE
Test test_cast_format_locale fails on NetBSD

### ISSUE THREAD

**Issue by cheusov** [wireservice/agate#782]
Test test_cast_format_locale fails on NetBSD because its locale database is a bit different from glibc's database.
This test fails trying to convert 01-Dez-1994.
On NetBSD de_DE.UTF-8 locale says that months for de_DE are "Dez.", "Jan." etc., not "Dez", "Jan" etc,

**Comment by jpmckinney** [comment]
Thanks! I updated the test.
