### ISSUE TITLE
`RuntimeWarning: Error sniffing CSV dialect: Could not determine delimiter` for csv with one column

### ISSUE THREAD

**Issue by mxr** [wireservice/agate#783]
See the below repro:

```console
$ tail example.csv example.py
==> example.csv <==
a
100

==> example.py <==
from agate import csv

with open("example.csv") as f:
    csv.Sniffer().sniff(f.read())
$ python example.py
/Users/mxr/tmp/example.py:4: RuntimeWarning: Error sniffing CSV dialect: Could not determine delimiter
  csv.Sniffer().sniff(f.read())
```

Since my csv has one column and no common delimiters (ex: comma, tab, space, semicolon, etc) I was surprised to get a `RuntimeWarning`. Would you consider updating the sniffer to not warn in this case? Thank you!

**Comment by jpmckinney** [comment]
Our Sniffer is just a small wrapper around https://docs.python.org/3/library/csv.html#csv.Sniffer that turns an error into a warning.

It’s impossible to determine that a file has only one column, considering any character can be used as a delimiter.

A one column file is very unusual as an input to a library for delimited files. If you don’t like the warning, just catch it and ignore it: https://docs.python.org/3/library/warnings.html

**Comment by mxr** [comment]
Thanks for explaining!
