### ISSUE TITLE
Feature Request: Move csvclean functionality here (from csvkit)

### ISSUE THREAD

**Issue by DeflateAwning** [wireservice/agate#784]
Based on the discussion in https://github.com/wireservice/csvkit/issues/1269, it seems like it would make sense to move the csvclean utility code/logic to this repo so it can be called via a function in Python.

The two places the code is defined are listed as:
1. 100 lines: https://github.com/wireservice/csvkit/blob/master/csvkit/utilities/csvclean.py
2. 150 lines: https://github.com/wireservice/csvkit/blob/master/csvkit/cleanup.py

**Comment by jpmckinney** [comment]
I'll close this issue, as csvclean is unlikely to fit with agate.
